# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_data": "01_core.ipynb",
         "Dataset": "01_core.ipynb",
         "DataBunch": "01_core.ipynb",
         "Learner": "01_core.ipynb",
         "get_dls": "01_core.ipynb",
         "get_model": "01_core.ipynb",
         "get_learner": "01_core.ipynb",
         "accuracy": "01_core.ipynb",
         "camel2snake": "01_core.ipynb",
         "Callback": "01_core.ipynb",
         "TrainEvalCallback": "01_core.ipynb",
         "listify": "01_core.ipynb",
         "Runner": "01_core.ipynb",
         "AvgStats": "01_core.ipynb",
         "AvgStatsCallback": "01_core.ipynb",
         "Recorder": "01_core.ipynb",
         "ParamScheduler": "01_core.ipynb",
         "annealer": "01_core.ipynb",
         "sched_lin": "01_core.ipynb",
         "sched_cos": "01_core.ipynb",
         "sched_no": "01_core.ipynb",
         "sched_expo": "01_core.ipynb",
         "cos_1cycle_anneal": "01_core.ipynb",
         "torch.Tensor.ndim": "01_core.ipynb",
         "combine_scheds": "01_core.ipynb"}

modules = ["l10_anneal.py"]

doc_url = "https://weilainicolas.github.io/fastai_lai_lib/"

git_url = "https://github.com/weilainicolas/fastai_lai_lib/tree/master/"

def custom_doc_links(name): return None
